apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretland-deployment
  labels:
    app: secretland
spec:
  selector:
    matchLabels:
      app: secretland
  template:
    metadata:
      labels:
        app: secretland
    spec:
      containers:
      - image: 745892092221.dkr.ecr.us-east-1.amazonaws.com/railsapp:20
        name: rails
        ports:
        - containerPort: 3000
        env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: secretland-secrets
                key: rails-master-key
                name: mysecret
                key: RDS_HOSTNAME
                name: mysecret
                key: RDS_DB_NAME
                name: mysecret
                key: RDS_PORT
                name: mysecret
                key: RDS_USERNAME
                name: mysecret
                key: RDS_PASSWORD
