apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  RDS_USERNAME: cG9zdGdyZXM=
  RDS_PASSWORD: cG9zdGdyZXM=
stringData:
  RDS_DB_NAME: "pmdb"
  RDS_HOSTNAME: "dev-db.c8yyyruivp28.us-west-2.rds.amazonaws.com"
  RDS_PORT: "5432"
